### ISSUE TITLE
rev_D

### ISSUE THREAD

**Issue by sxia1** [MaryannFoley/topherlings#5]
For the different categories, the user should be able to delve into more specific topics from the main topics. Perhaps group bubbles on the page to represent different topics. Hovering over a bubble and having all its information appear on the side in a text box would be convenient.
Displaying the bubbles on a set of axis would aid in visualizing the data. X axis can be the time and the Y axis can be percentage of goal completed or money raised. This can also show when these types of projects started gaining traction.

**Comment by joyceliaoo** [comment]
We will be doing the bubble grouping, thank you for the suggestions!
